Algoritmo "Conte De 10 Ate 0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruno menezes Diniz
// Data atual  : 16/12/2024
Var
   contador:inteiro
Inicio
   contador <- 10
   enquanto (contador >=0)   faca
      escreval (contador)
      contador <- Contador-1

   fimEnquanto
   escreva ("Terminei de contar")



Fimalgoritmo