Algoritmo "Contar de 100 até 3 usando o DO WHILE"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/12/2024
Var
   cont,num:inteiro


Inicio
   cont <-100

   Escreval ("CONTE DE 100 até 3.")
   enquanto (cont >=3) faca
   escreva (cont)

      cont <- cont-1
   fimEnquanto





Fimalgoritmo