Algoritmo "departamento de transito"

Var
   ano_atual,ano_nasc,idade:inteiro

Inicio

      escreva ("Digite o ano atual:")
      leia (ano_atual)

      escreva ("Digite o ano nasc:")
      leia (ano_nasc)
      
      idade <- (ano_atual - ano_nasc)
      
      se(idade >=18) entao
            escreval("Apto para Dirigir")
      senao
            escreva ("Nao esta apto para dirigir")
            fimse
      




Fimalgoritmo