Algoritmo "Ex 04 usando a estrutura for"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/02/2025
Var
   num,i:inteiro


Inicio
   escreva ("Digite um número: ")
   leia (num)
     para i <- 0 ate num faca
     escreva(i,",")
     fimpara
     escreva (" Fim!")




Fimalgoritmo