Algoritmo "Ex 03 usando a estrutura for"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/02/2025
Var
   i,num,res:inteiro


Inicio

   escreva ("Digite um número: ")
   leia(num)
   para i <- 1 ate 10 faca
      res <- num * i
      escreval(num," x",i," =",res)
   fimpara

Fimalgoritmo