Algoritmo "Idade passagem por referencia "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/01/2025
Var
   idade:inteiro

procedimento idade_teste(var I:inteiro)
inicio
   I <-40


fimprocedimento


Inicio

   idade_teste(idade)
   escreva ("O usúario possui ",idade," anos")






Fimalgoritmo