Algoritmo "Conta 1 ate 10 usando o Do while"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruno Menezes Diniz
// Data atual  : 24/12/2024
Var
   cont:inteiro


Inicio

   cont <-1
   repita
   escreval (cont)
   
   cont <- cont+1
   ate (cont >10)







Fimalgoritmo