Algoritmo "teste Vetor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2025
Var


   v:vetor[1..6] de inteiro
   C:inteiro

Inicio

   para C <-1 ate 6 faca
   escreva ("Digite o " , C ," valor: ")
   leia(v[c])

   fimpara


   para C <-1 ate 6 faca
   escreva ("{",v[c],"}")
   
   fimpara

Fimalgoritmo